Repository Monitoring-Mtl/PyTransit-MicroServices, pull requests merged in 2024-03, with the labels that each got.

#73 change current version
  .github/workflows/lint-test-workflow.yml
  .github/workflows/on-pr-workflow.yml
  .github/workflows/security-analysis-workflow.yml
  package-lock.json
  package.json
Labels: bug, devops

#74 Descriptions and missing Triggers
  STM_Services/STM_Analyse_Daily_Stops_Data/main.py
  samconfig.toml
  template.yml
Labels: enhancement, STM

#79 Patch versioning
  .github/workflows/on-push-workflow.yml
  template.yml
Labels: bug

#83 Fix Daily stops info functions
  STM_Services/STM_Analyse_Daily_Stops_Data/main.py
  template.yml
Labels: bug, STM

#84 Added missing permission for Bixi logs
  template.yml
Labels: bug, Bixi

#85 Full fix CreateInfo and partial fix Analyze
  STM_Services/STM_Analyse_Daily_Stops_Data/main.py
  STM_Services/STM_Create_Daily_Stops_Info/main.py
  template.yml
Labels: bug, STM

#88 Removed Aliases as targets and fix for Analyze
  STM_Services/STM_Analyse_Daily_Stops_Data/main.py
  template.yml
Labels: bug
